[package]
name = "monte_carlo"
version = "0.1.0"
edition = "2021"
authors = ["Dolpic <dolpic@outlook.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rand = "0.8.5"
statrs = "0.16.0"
getrandom = { version = "0.2", features = ["js"] }